name: features_stack_management
resolution: workspace
description: Stack management features for App
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # Internal packages
  presentation_components:
    path: ../../presentation/components
  core_stack_flutter:
    path: ../../core/stack_flutter
  core_themes:
    path: ../../core/themes
  core_foundation_flutter:
    path: ../../core/foundation_flutter

  # External packages
  rinne_graph:
    git:
      url: https://github.com/szktty/rinne-graph.git
      ref: develop
  file_picker: ^10.1.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.2

flutter:
