include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/generated/**'
    - 'test/**'
  errors:
    todo: ignore
    invalid_annotation_target: ignore
    deprecated_member_use: ignore

linter:
  rules:
    avoid_print: false
    deprecated_member_use_from_same_package: ignore

custom_lint:
  rules:

