name: core_samples
resolution: workspace
description: Core package for sample stack management
version: 1.0.0

environment:
  sdk: ^3.7.0
  flutter: ">=3.41.2"

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  core_stack_common:
    path: ../stack_common
  core_stack_flutter:
    path: ../stack_flutter
  core_graph_common:
    path: ../graph_common
  core_exchange:
    path: ../exchange

  flutter_riverpod: ^3.0.0
  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/meiji/
    - assets/graph_of_the_gods/
    - assets/graph_of_the_gods_ja/
    - assets/crime_and_punish_ja/
    - assets/crime_and_punish_en/
