name: core_foundation_common
description: Platform-independent foundational utilities for App.
publish_to: none
resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  meta: ^1.11.0
  path: ^1.9.0
  uuid: ^4.5.1

dev_dependencies:
  test: ^1.28.0
  lints: ^5.0.0
