name: features_welcome
resolution: workspace
description: App welcome screen feature package
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=3.41.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^4.0.0
  presentation_components:
    path: ../../presentation/components
  lucide_icons_flutter: ^3.0.5
  file_picker: ^10.1.0
  path: ^1.9.0

  core_stack_flutter:
    path: ../../core/stack_flutter
  core_stack_common:
    path: ../../core/stack_common
  core_settings:
    path: ../../core/settings
  core_themes:
    path: ../../core/themes
  core_foundation_flutter:
    path: ../../core/foundation_flutter
  features_stack_management:
    path: ../stack_management
  desktop_drop: ^0.6.0
  cross_file: ^0.3.4+2
  url_launcher: ^6.3.2
  core_samples:
    path: ../../core/samples

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  riverpod_generator: ^4.0.0
