name: features_settings
resolution: workspace

environment:
  sdk: ^3.7.0
  flutter: ">=3.41.2"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^4.0.0
  shared_preferences: ^2.2.2
  lucide_icons_flutter: ^3.0.5
  core_foundation_flutter:
    path: ../../core/foundation_flutter
  core_app_config:
    path: ../../core/app_config
  presentation_components:
    path: ../../presentation/components
  core_themes:
    path: ../../core/themes
  core_settings:
    path: ../../core/settings
  app:
    path: ../../app

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  freezed: ^3.0.0
  json_serializable: ^6.8.0
  very_good_analysis: ^9.0.0
  riverpod_generator: ^4.0.0
