name: presentation_components
resolution: workspace

environment:
  sdk: ^3.7.0
  flutter: ">=3.41.2"

dependencies:
  flutter:
    sdk: flutter
  features_settings:
    path: ../../features/settings
  core_themes:
    path: ../../core/themes
  searchfield: ^2.0.0
  core_graph_flutter:
    path: ../../core/graph
  uuid: ^4.5.1
  figma_squircle: ^0.6.3
  textfield_tags: ^3.0.1
  lucide_icons_flutter: ^3.0.5
  popover: ^0.3.1
  material_table_view: ^5.5.0
  pluto_grid: ^8.0.0
  dots_indicator: ^4.0.1
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^4.0.0
  features_record_editor:
    path: ../../features/record_editor
  multi_split_view: ^3.2.1

  core_foundation_flutter: any
  features_pathfinder: any
  core_stack_flutter: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^4.0.0
  build_runner: ^2.4.14

flutter:
