import 'package:flutter/material.dart';
import 'package:fonde_ui/fonde_ui.dart'
    show FondeDialog, FondeDialogImportance, showFondeDialog;
export 'package:fonde_ui/fonde_ui.dart'
    show FondeDialog, FondeDialogImportance, showFondeDialog;

typedef AppDialog = FondeDialog;
typedef DialogImportance = FondeDialogImportance;

Future<T?> showAppDialog<T>({
  required BuildContext context,
  String? title,
  String? subtitle,
  Widget? child,
  WidgetBuilder? builder,
  Widget? footer,
  double? width,
  double? height,
  double? heightRatio,
  double? maxWidth,
  double? maxHeight,
  double? minWidth,
  double? minHeight,
  EdgeInsetsGeometry? padding,
  double? headerBottomSpacing,
  double? dividerHorizontalPadding,
  double elevation = 8.0,
  double? cornerRadius,
  double? cornerSmoothing,
  Color? backgroundColor,
  bool barrierDismissible = true,
  Color? barrierColor,
  String? barrierLabel,
  bool useSafeArea = true,
  bool useRootNavigator = true,
  RouteSettings? routeSettings,
  Offset? anchorPoint,
  TraversalEdgeBehavior? traversalEdgeBehavior,
  bool noDarkBackground = false,
  bool showCloseButton = false,
  VoidCallback? onClose,
  DialogImportance importance = DialogImportance.standard,
  bool showDivider = true,
}) {
  return showFondeDialog<T>(
    context: context,
    title: title,
    subtitle: subtitle,
    child: child,
    builder: builder,
    footer: footer,
    width: width,
    height: height,
    heightRatio: heightRatio,
    maxWidth: maxWidth,
    maxHeight: maxHeight,
    minWidth: minWidth,
    minHeight: minHeight,
    padding: padding,
    headerBottomSpacing: headerBottomSpacing,
    dividerHorizontalPadding: dividerHorizontalPadding,
    elevation: elevation,
    cornerRadius: cornerRadius,
    cornerSmoothing: cornerSmoothing,
    backgroundColor: backgroundColor,
    barrierDismissible: barrierDismissible,
    barrierColor: barrierColor,
    barrierLabel: barrierLabel,
    useSafeArea: useSafeArea,
    useRootNavigator: useRootNavigator,
    routeSettings: routeSettings,
    anchorPoint: anchorPoint,
    traversalEdgeBehavior: traversalEdgeBehavior,
    noDarkBackground: noDarkBackground,
    showCloseButton: showCloseButton,
    onClose: onClose,
    importance: importance,
    showDivider: showDivider,
  );
}
